db:
  user: pguser
  name: jhe-test
  password: test-password
  host: jhe-test-postgres

env:
  SITE_URL: http://localhost:8081

service:
  type: ClusterIP

ingress:
  enabled: true

mcp:
  enabled: true
  ingress:
    enabled: true
    path: /mcp
  service:
    type: ClusterIP

postgres:
  enabled: true
  serviceName: jhe-test-postgres

seed:
  enabled: true
  hook: post-upgrade
  args:
    - --flush-db
    - --with-rich
