apiVersion: v2
name: jhe
version: 0.0.1-set.by.chartpress
appVersion: "0.0.11"
description: JupyterHealth helm chart
keywords: [jupyter, jupyterhealth]
home: https://jupyterhealth.org
sources:
  - https://github.com/jupyterhealth/helm-charts
icon: https://jupyterhealth.org/favicon-180.png
kubeVersion: ">=1.31.0-0"
