# JHE stuff

db:
  name: postgres
  user: postgres
  password: ""
  host: ""
  port: 5432

debug:
  enabled: false

image: ghcr.io/jupyterhealth/jupyterhealth-exchange:0.0.13.dev102-gb582f941f
imagePullPolicy:

migrate:
  enabled: true

args: []
volumeMounts: []
workers: 2

env:
  SITE_TITLE: JupyterHealth Exchange
  SITE_URL: ""

# first-time generate these secret environment variables
_secret_env:
  - SECRET_KEY

resources: {}

# kubernetes stuff
nameOverride: ""
fullnameOverride: ""

replicas: 1

pdb:
  enabled: false
  spec:
    maxUnavailable:
    minAvailable: 1

service:
  type: LoadBalancer
  labels: {}
  annotations: {}
  nodePorts:
    http: # @schema type:[integer, null]; minimum:0
    https: # @schema type:[integer, null]; minimum:0
  disableHttpPort: false
  extraPorts: []
  externalIPs: []
  loadBalancerIP:
  loadBalancerSourceRanges: []
  ipFamilyPolicy: PreferDualStack
  ipFamilies: []

httpRoute:
  enabled: false
  annotations: {}
  hostnames: []
  gateway:
    name: your-gateway
    namespace: "" # required for a gateway resource in another namespace

ingress:
  enabled: false
  annotations: {}
  ingressClassName:
  hosts: []
  path: /
  pathSuffix:
  pathType: Prefix
  tls: []
  extraPaths: []

livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 13

readinessProbe:
  enabled: true
  initialDelaySeconds: 3
  periodSeconds: 11

mcp:
  image: ghcr.io/jupyterhealth/jupyterhealth-exchange-mcp:4b121c2
  enabled: false
  replicas: 1
  resources: {}

# these are only for testing
seed:
  enabled: false
  hook: post-install
  args: []

postgres:
  enabled: false
  image: postgres:18
  serviceName: ""
