repos:
  # Autoformat: Python code, syntax patterns are modernized
  - repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4 # frozen: v3.21.2
    hooks:
      - id: pyupgrade

  # Autoformat: Python code
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 4160603246a6b365d4a2af661c6d71b0a0f50478  # frozen: 26.5.1
    hooks:
      - id: black

  # Autoformat: Python code
  - repo: https://github.com/pycqa/isort
    rev: dac090ce4d9ee313d086e2e89ab1acb8c2664fa1  # frozen: 9.0.0a3
    hooks:
      - id: isort
        args:
          - --profile=black

  # Autoformat: markdown, yaml (but not helm templates)
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 515f543f5718ebfd6ce22e16708bb32c68ff96e1  # frozen: v3.8.3
    hooks:
      - id: prettier
        exclude: ".*/templates/.*"

  # Reset Chart.yaml version and values.yaml image tags
  - repo: https://github.com/jupyterhub/chartpress
    rev: 4f07d9b88cc05450552657d4d4c6be5e56db5a07  # frozen: 2.4.0
    hooks:
      - id: chartpress

  # Linting: Python code (see the file .flake8)
  - repo: https://github.com/PyCQA/flake8
    rev: "d93590f5be797aabb60e3b09f2f52dddb02f349f" # frozen: 7.3.0
    hooks:
      - id: flake8

  # github actions security checks
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 9257c6050c0261b8c57e712f632dc4a8010109a9  # frozen: v1.25.2
    hooks:
      - id: zizmor
        args:
          - --fix=all

  # Autoformat: Bash scripts
  - repo: https://github.com/lovesegfault/beautysh
    rev: 885128fe2600889194c69fa19326cf55a3462777 # frozen: v6.4.3
    hooks:
      - id: beautysh

  # shell scripts
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 99470f5e12208ff0fb17ab81c3c494f7620a1d8d # frozen: v0.11.0
    hooks:
      - id: shellcheck

ci:
  autoupdate_schedule: monthly
