{{- if .Values.postgres.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "jhe.fullname" . }}-postgres
  labels:
    {{- include "jhe.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  POSTGRES_USER: {{ .Values.db.user | b64enc | quote }}
  POSTGRES_DB: {{ .Values.db.name | b64enc | quote }}
{{- end }}
