kind: Secret
apiVersion: v1
metadata:
  name: {{ template "jhe.fullname" . }}
  labels:
    {{- include "jhe.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.db }}
  DB_{{ $key | upper }}: {{ $value | print | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.env }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
  # some default values (e.g. SECRET_KEY)
  # that should be set once
  {{- $k8s_state := lookup "v1" "Secret" .Release.Namespace (include "jhe.fullname" .) | default (dict "data" (dict)) }}
  {{- $Values := .Values }}
  {{- range $key := .Values._secret_env }}
  {{- if not (hasKey $Values.env $key) }}
    {{- $key | quote | nindent 2 }}:
    {{- if hasKey $k8s_state.data $key }}
      {{ index $k8s_state.data $key | quote }}
    {{- else }}
      {{ randAlphaNum 32 | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
