apiVersion: v1
kind: Service
metadata:
  name: {{ include "jhe.fullname" . }}
  labels:
    {{- include "jhe.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: jhe
    {{- include "jhe.matchLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
