{{- $self := .Values.mcp }}
{{- if $self.enabled }}
{{- $component := "mcp" }}
{{- $name := printf "%s-%s" (include "jhe.fullname" .) $component }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/component: {{ $component }}
    {{- include "jhe.labels" . | nindent 4 }}
spec:
  replicas: {{ $self.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ $component }}
      {{- include "jhe.matchLabels" . | nindent 6 }}
  {{- if .Values.deploymentStrategy }}
  strategy:
    {{- .Values.deploymentStrategy | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ $component }}
        {{- include "jhe.matchLabels" . | nindent 8 }}
      annotations:
        # This lets us autorestart when the secret changes!
        checksum/secret: {{ include (print .Template.BasePath "/mcp/secret.yaml") . | sha256sum }}
        {{- if $self.annotations }}
        {{- $self.annotations | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
    spec:
      nodeSelector: {{ toJson .Values.nodeSelector }}
      containers:
        - name: jhe-mcp
          image: {{ $self.image }}
          {{- with $self.command }}
          command:
            {{- .  | toYaml | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with $self.args }}
          args:
            {{- .  | toYaml | trimSuffix "\n" | nindent 12 }}
          {{- end }}

          {{- with $self.resources }}
          resources:
            {{- . | toYaml | trimSuffix "\n" | nindent 12 }}
          {{- end }}
          {{- with .Values.imagePullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ $name }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: JHE_BASE_URL
              value: http://{{ template "jhe.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            - name: MCP_HTTP_PORT
              value: "8000"
          ports:
            - containerPort: 8000
              name: http
          {{- if $self.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ $self.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $self.livenessProbe.periodSeconds }}
            httpGet:
              path: /health
              port: http
              httpHeaders:
                - name: Host
                  value: localhost
          {{- end }}
          {{- if $self.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ $self.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $self.readinessProbe.periodSeconds }}
            httpGet:
              path: /health
              port: http
              httpHeaders:
                - name: Host
                  value: localhost
          {{- end }}
{{- end }}
