{{- $self := .Values.mcp }}
{{- $component := "mcp" }}
{{- $name := printf "%s-%s" (include "jhe.fullname" .) $component }}
{{- if .Values.mcp.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $name }}
  labels:
    {{- include "jhe.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $self.env }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
  # some default values (e.g. MCP_BROKER_KEY)
  # that should be set once
  {{- $k8s_state := lookup "v1" "Secret" .Release.Namespace $name | default (dict "data" (dict)) }}
  {{- range $key := $self._secret_env }}
  {{- if not (hasKey $self.env $key) }}
    {{- $key | quote | nindent 2 }}:
    {{- if hasKey $k8s_state.data $key }}
      {{ index $k8s_state.data $key | quote }}
    {{- else }}
      {{ randAlphaNum 32 | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
